name: bookly_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  bloc: ^9.1.0
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  font_awesome_flutter: ^10.10.0
  get_it: ^9.0.5
  go_router: ^16.3.0
  google_fonts: ^6.3.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
